---
title: "Untitled"
format: html
---

- palisads = a community
- felt community in undergrad
- lost it when I graduated bc I no longer knew what i wanted to do
- had to find a new one in grad school / for DS career 

---

`Hello, world!` - finding and fostering your learning community and support network 

---

Thank you so much for that lovely introduction, ___ :) And thank you all for being here—especially so early on a Saturday morning.

---

Again, I’m Sam, and today I want to talk about something that’s deeply meaningful to me: community.
That might sound a little obvious—maybe even a bit cheesy. Some of you might be thinking, "Sure, we already know community is important. We’re part of one right now."

But I really do believe that community is so foundational to both our personal and professional growth and happiness that it deserves its own 45-minute spotlight.

---

I want to start with a bit of honesty — and maybe even some vulnerability.

This talk was really hard for me to put together. I floundered for what felt like a lifetime.

When Jack and Jessie first asked me to keynote back in December, I was like, "heck yeah!" I’d never been invited to do something like this before—it felt like such an honor. I was also in the thick of prepping for Winter Quarter teaching, so I told myself, “This won't be a problem, I don't quite have time now, but I’ll come back to this in the spring. Tons of time.”

And of course… spring rolled around. Starting a talk is always the hardest part for me, so instead of doing that, I took up a couple other projects, found some new distractions. I kept pushing it off and off until, finally, about three weeks ago, I sat down to make an outline—and came up completely blank.

---

I’d write a few lines. Erase them. Write. Delete. Repeat.

After a frustrating week of this, I turned to my husband and said, “I don’t think I can do this. Why did they even ask me? Out of all the amazing people that could’ve given this talk, why me? What qualifies me, someone who's still fairly early-early, absolutely learning as I goes, to stand up here and talk to anyone about anything data science, career, etc.?” I was feeling really really inadequate and incapable.

Has anyone here ever felt that way about something important they had to do?

Yeah. It’s kinda the worst.

---

It took me until two weeks ago to realize what was going on:

I was dealing with a massive case of imposter syndrome!

The irony of that, was I had already planned to include themes about imposter syndrome throughout this talk, because it's huge part of why building and fostering community has been so instrumental to my career growth. And I didn’t even noticed it creeping in. 

---

So today, I want to share some personal stories from my own journey (the ups, the downs, the twists, the turns) and role that community has played in getting to me to where I am now. And throughout, I want to take some time for a bit of small group discussion so that you can reflect on the people, spaces, and networks that have supported you—and the ones you might want to nurture next.

How does that sound?

---

I want to pause here real quick though, and ask you all, 

"What communities are you currently a part of?" (don't need to be professional or academic communities)
"What about those communities are most impactful or important to you, and why?"
"Are there particular aspects of those communities that you'd like to seek out in your professional communities?"

I'll start: I never liked working out at the gym, mostly because I was intimidated. I used to run a lot, but I've had a couple surgeries that prevent me from doing that anymore. Back in 2022, I joined our local Y and started taking classes. Those classes are full of regulars who become your fast friends. When someone misses more than 1 day, they're all asking if you're okay. They motivate me to get myself there regularly, to lift heavier and push myself to get stronger. I love that about them. If I were to try that at home, I would not be where I am today.

Okay your turn! (think-pair-share)

---

I ended up in grad school bc I didn't know what to do when I finished undergrad. Loved college and did well. Pursued a degree in Marine Biology and thought I knew exactly what I wanted from life. Graduated and realized I was totally lost. I was unsuccessful in landing a job related to my degree, so ended up working as a receptionist in a doggy daycare for a year. I finally took the leap and ended up here at UCSB -- didn't know what I was doing, only applied here because I knew one of the new faculty from one of my undergraduate courses. I was excited about field and lab work -- my thesis explored temperature effects on spiny lobster metabolism and foraging behavior. It was quite theoretical and I really did not look forward to getting my hands on my own data. I came in with 0 programming experience and hadn't taken a stats class in years. During my first week, my advisor handed me some long-term temperature data collected at one of our coastal rocky reef sites here in Santa Barbara (Mohawk, for anyone who's familiar) and asked for some summary stats and basic data viz. WHAT. It took me a literal month to figure out how to install and configure R / RStudio and read in a csv file. Seems almost unimaginable now. But I felt absolutely defeated. How was I going to survive an entire Master's degree???

---

Lesson 1: The first big step is the hardest -- make it a baby step!

My friend An and I decided to pair up as accountabilibuddies and meet weekly to work through R for Data Science -- kinda the bible for budding R users.

https://r4ds.had.co.nz/
https://r4ds.hadley.nz/

[show pick of github repo, both editions of book]

---

It was around this time that I was able to enroll in my first real course. My department didn't offer any in-house courses on programming, but I begged the Bren School (where I now work) to let me into Allison Horst's Statistics and Data Analysis in Environmental Science course. She did! and within a day, my world was changed. This was the first time I had ever heard the term "Data Science", and Allison showed me that was not only approachable, but perhaps even fun?? 

---

Lesson 2: Join an organized community

R-Ladies global org with local chapters. But there are others all over the place.
Started in 2018. What it made me realize was that I was not alone. All the attendees were also beginning their journeys and looking for others intersted in learning together.

They can also look different from this: 
- TidyTuesday coding club
- NCEAS Coding Club & Hacky Hours https://github.com/nceas-coding-club

Sometimes organized content, other times it was just an opportunity to work on your own thing with others around you

---

Lesson 3: or create your own (and try to keep it simple, for your own sanity)

"#tidytuesday offers a no-stress, low-effort coding club option for organizers"

> Figure out the goals of your coding club first, try to anticipate the level of most attendees, and choose a format that will set them up to meet those goals.

https://openscapes.org/blog/2019-05-02-tidy-tuesday-coding-club/

important to foster spaces that invite others in

---

Lesson 4: Volunteer to present, even when you don't feel "ready"

- Julie Lowndes talking about `{here}` inspired An and I to give a workshop on the `{tidyverse}`

---

Lesson 5: (related) everyone has something to learn and to share

Tips & Tricks event during covid

---

<!-- --- -->

<!-- It took me a while to figure out what I wanted professionally. And even longer to understand the power of community. For a while, I felt like I was just… drifting. -->

<!-- --- -->

<!-- My journey, like many of yours, starts in undergrad -- for as long I can remember, I wanted to be a marine biologist (I've been told that's a millennial thing, that we all wanted to be marine biologists).  -->

<!-- I honestly did really great in college -- I knew how to study, I got good grades, I landed a couple really cool research opportunities. I felt on top of the world.  -->

<!-- Then I graduated. And it was like someone flipped a switch. Suddenly, I felt SO lost. I applied to countless jobs and didn't get an interview for any of them. I started questioning everything. -->

<!-- --- -->

<!-- I needed a paycheck, so I took a minimum wage job as a receptionist at a doggy daycare. It was… not my dream job. I didn’t know how to get from there to anywhere else. -->

<!-- Eventually, I took a minimum wage job working as a receptionist at a doggy daycare. It was rough, I didn't enjoy it and I didn't know how to move forward. I did not enjoy my time there, and I did not know how to really get myself out of it. A lecturer I had in one of my undergraduate marine bio courses that I looked up to a lot and kept in touch with over the years let me know he was joining faculty at UCSB in the EEMB department. I didn't know why I wanted to go to grad school or what I might do with a graduate degree. But I didn't know what other next step to take. No one in my family had gone to graduate school before, I didn't have any friends who were pursuing grad school at the time, and I just didn't really know what I was doing. Applied just to UCSB with the intention of doing a PhD, switched to Masters during the application process, applied to a bunch of fellowships and didn't get any of them. All of my lab mates did. I felt totally out of place.  -->

<!-- --- -->

<!-- And then I realized I didn't enjoy research, or at least the research I was doing -- super theoretical. I did enjoy getting to spend time in the field and lab. But was terrified of actually finally getting data in hand bc what the heck was I going to do with it at that point. I hadn't taken a stats course in a long while, I didn't know the first thing about programming. I was handed some long-term temperature data collected at some rocky reef sites here off SB and it took me a whole month to figure out how to download and install R/RStudio and how to read in a CSV file. Woof. I was feeling so out of place. -->

---



---

Hope by the end we can all acknowledge the following:

Community provides a safe and supportive space to learn and fail. This is so critical for combating imposters syndrome. Finding and fostering community takes some work, and it's helpful to know yourself and your goals. Consider sharing those in a public way!

---

- put yourself out there (online, show up to a social group gathering, organize co-learning sessions with colleagues or classmates, tidytuesday)

---

Growing up, I was a student who knew exactly what she wanted to do when she grew up -- I wanted to be a Marine Biologist (I think it started with a VHS tape I would watch on repeat at my grandparents house that was just a bunch of underwater filmography set to orchestra music).

I was always a book worm, and I did really great in college -- I just really enjoyed studying, I knew how to do it well. I was surprised and bummed when I couldn't find a job when I graduated. I 

---

LESSONS LEARNED: 
- imposter syndrome fades in inclusive, supportive spaces
  - seek them out and contribute back back
- everyone has something to share and something to learn 
  - julie lowndes sharing the `{here}` package
  - putting on the tips & tricks event
- RELATED: you don't have to be an expert to contribute meaningfully
  - I'm an early career, new learner. I think this makes me a more impactful educator because I'm often learning things to share with studetns and can recognize potential pitfalls, confusing points, challenges that students will encounter, because I recently encountered them myself


---


---

-- this is super outside my comfort zone! Currently, my comfort zone is teaching. I love diving into a topic, and sharing that knowledge with folks who are interested in it. I love thinking about creative pedagogical approaches for engaging students in the learning process. Two years though, I would have felt completely out of my element. 

Currently, my comfort zone is teaching -- I love being in front of a class and sharing what I know or what I've learned about a topic that students are excited about. Two years ago, that would absolutely terrfied me. Three years before that, I was just getting comfor

---

Two years ago, I taught my first real big course -- a Data Viz course for the Bren School's MEDS program. And building that course (then teaching it) felt like an insurmoutable task. I definitely cried a couple times, told myself I had no reason to be the one in charge of teaching these graduate students anything about Data Viz.

---

---
---

I'm Sam! If you had told me a few years ago that I'd be standing here today, I wouldn't have believed you. I spend most of my schooling years being absoltuely terried of all things data and computers


---

I was really terrified of all things data and computers. I was really great at being an undergrad -- I knew how to study, and I knew how to work hard, and it just clicked. But when I graduated, I suddenly felt really lost. I applied to a bunch of jobs in the marine sciences, but didn't get interviews for any of them. I ended up taking a job as a receptionist at a doggy daycare and felt directionless. Applied to graduate school, which led me here. I worked on spiny lobster, and was happy to spend time in the field and lab collecting data, but really wasn't looking forward to actually having it all in hand.

I was always "bad at math," almost failed by AP bio class in high school (not because I wasn't trying, but because I was a slow learner)

I had never even heard of the term data science until I was a year into graduate school

photos: 
- undergrad three seas
- BBB
- lobsters / lab
- allison's class


---

mentimeter: what's next? grad school, work, i don't know yet 

---

putting yourself out there can be really scary sometimes
- I saw julie lowndes do it 
- I volunteered with my bestie An to do it (I was so scared! someone asked me a question I didn't know the answer to, and I froze; slowly people in the audience all chimed into help answer the question collectively)

Include pic of Sam / An

---

RLadies rotating curator
- led me to build my first map


---

So how can you prepare yourself to best engage with online communities?

- You've built your personal websites, now infuse them with YOU! develop your personal brand 


